version: "2.4"
services:
  db:
    image: mariadb:latest
    env_file:
      - config/mysql.env
      - config/mysql_root.env
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql # To override random volume name
    networks:
      - backend
    restart: on-failure

  app:
    build: ./back
    env_file:
      - config/flask.env
      - config/mysql.env
      - config/local.env
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ./back:/app/:ro
    networks:
      - backend
      - frontend
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:5000 || 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

  front:
    build: ./front
    env_file: config/node.env
    expose:
      - "3000"
    user: node 
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - ./front/public:/home/node/app/public
      - ./front/src:/home/node/app/src
      - user-pictures:/data # To store users pictures in persistent storage
    command: "npm start"
    networks:
      - frontend
    restart: on-failure

  tests_back:
    build: ./back/tests
    volumes:
      - ./back/tests:/tests
    networks:
      - frontend


networks:
  backend:
  frontend:

volumes:
  user-pictures:
  db-data: