version: "2"
services:
  app:
    build: ./dockerfiles/flask
    links:
      - db
    ports:
      - "80:5000"
    expose:
      - "5000"
    environment: 
      FLASK_ENV: development
      FLASK_APP: matcha.py
      SQLALCHEMY_POOL_RECYCLE: 599
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./app:/app/:ro
    networks:
      - backend

  db:
    image: mariadb:latest
    ports:
      - "32000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: matcha
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend


networks:
  backend: