version: "2"
services:
  app:
    build: ./dockerfiles/flask
    links:
      - db
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment: 
      FLASK_ENV: development
      FLASK_APP: matcha.py
      SECRET_KEY: "J'aime manger des pommes"
      SQLALCHEMY_POOL_RECYCLE: 599
      SQLALCHEMY_ECHO: 'true'
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./app:/app/:ro
    networks:
      - backend
      - frontend

  db:
    image: mariadb:latest
    ports:
      - "32000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: matcha
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql # To override random volume name
    networks:
      - backend

  front:
    image: "node:latest"
    links:
      - app
    expose:
      - "3000"
    user: node 
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./front:/home/node/app
    command: "npm start"
    networks:
      - frontend

volumes:
  db-data:

networks:
  backend:
  frontend: