version: "2"
services:
  app:
    build: ./back
    env_file:
      - config/flask.env
      - config/mysql.env
      - config/local.env
    links:
      - db
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment: 
      FLASK_ENV:
      FLASK_APP:
      MYSQL_USER:
      MYSQL_PASSWORD:
      FLASK_GMAIL:
      FLASK_GMAIL_PASSWORD:
      REACHABLE_HOST:
    volumes:
      - ./back:/app/:ro
    networks:
      - backend
      - frontend

  db:
    image: mariadb:latest
    env_file:
      - config/mysql.env
      - config/mysql_root.env
    ports:
      - "32000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - db-data:/var/lib/mysql # To override random volume name
    networks:
      - backend

  front:
    build: ./front
    env_file: config/node.env
    links:
      - app
    expose:
      - "3000"
    user: node 
    working_dir: /home/node/app
    environment:
      NODE_ENV:
      REACHABLE_HOST:
    ports:
      - "3000:3000"
    volumes:
      - ./front/public:/home/node/app/public
      - ./front/src:/home/node/app/src
      - user-pictures:/data # To store users pictures in persistent storage
    command: "npm start"
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  user-pictures:
  db-data: