version: "2"
services:
  app:
    build: ./dockerfiles/flask
    links:
      - db
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment: 
      FLASK_ENV: development
      FLASK_APP: matcha.py
      SECRET_KEY: '\xfd{H\xe5<\x95\xf9\xe3\x96.5\xd1\x01O<!\xd5\xa2\xa0\x9fR"\xa1\xa8'
      SQLALCHEMY_POOL_RECYCLE: 599
      SQLALCHEMY_ECHO: 'true'
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./app:/app/:ro
    networks:
      - backend

  db:
    image: mariadb:latest
    ports:
      - "32000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: matcha
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend


networks:
  backend: