version: "2"
services:
  app:
    build: ./back
    links:
      - db
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment: 
      FLASK_ENV: development
      FLASK_APP: matcha.py
      SQLALCHEMY_POOL_RECYCLE: 599
      SQLALCHEMY_ECHO: 'true'
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./back:/app/:ro
    networks:
      - backend
      - frontend

  db:
    image: mariadb:latest
    ports:
      - "32000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: matcha
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql # To override random volume name
    networks:
      - backend

  front:
    build: ./front
    links:
      - app
    expose:
      - "3000"
    user: node 
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./front/public:/home/node/app/public
      - ./front/src:/home/node/app/src
      - user-pictures:/data # To store users pictures in persistent storage
    command: "npm start"
    networks:
      - frontend

volumes:
  db-data:
  user-pictures:

networks:
  backend:
  frontend: